from __future__ import annotations

GOLDSRC_COMPONENTS = [
    {
        "name": "GoldSrc Engine",
        "subfolder": "",
        "repo_url": "https://github.com/FWGS/xash3d-fwgs",
        "repo_branch": "",
        "stable_commit": "e4600b5",
        "build_system": "waf",
        "estimated_time": 1,
        "estimated_space": 350,
    },
    {
        "name": "Half-Life",
        "subfolder": "valve",
        "repo_url": "https://github.com/FWGS/hlsdk-portable",
        "repo_branch": "hlfixed",
        "stable_commit": "78bc253",
        "build_system": "waf",
        "estimated_time": 1,
        "estimated_space": 60,
    },
    {
        "name": "Half-Life: Opposing Force",
        "subfolder": "gearbox",
        "repo_url": "https://github.com/FWGS/hlsdk-portable",
        "repo_branch": "opforfixed",
        "stable_commit": "654d15c",
        "build_system": "waf",
        "estimated_time": 1,
        "estimated_space": 60,
    },
    {
        "name": "Half-Life: Blue Shift",
        "subfolder": "bshift",
        "repo_url": "https://github.com/FWGS/hlsdk-portable",
        "repo_branch": "bshift",
        "stable_commit": "df5c272",
        "build_system": "waf",
        "estimated_time": 1,
        "estimated_space": 60,
    },
    {
        "name": "Deathmatch Classic",
        "subfolder": "dmc",
        "repo_url": "https://github.com/FWGS/hlsdk-portable",
        "repo_branch": "dmc",
        "stable_commit": "895b28d",
        "build_system": "waf",
        "estimated_time": 1,
        "estimated_space": 60,
    },
    {
        "name": "Counter-Strike",
        "subfolder": "cstrike",
        "repo_url": "https://github.com/Velaron/cs16-client.git",
        "repo_branch": "",
        "stable_commit": "5ee5639",
        "build_system": "cmake",
        "patch_dir_name": "cs16-client",
        "estimated_time": 3,
        "estimated_space": 350,
    },
]

HL2_SOURCE_COMPONENTS = [
    {
        "name": "Half-Life 2",
        "subfolder": "hl2",
        "repo_url": "https://github.com/nillerusr/source-engine",
        "repo_branch": "",
        "stable_commit": "ed8209c",
        "build_system": "waf",
        "patch_dir_name": "source-engine",
        "waf_game": "hl2",
        "estimated_time": 3,
        "estimated_space": 25,
    },
    {
        "name": "Half-Life 2: Lost Coast",
        "subfolder": "lostcoast",
        "repo_url": "https://github.com/nillerusr/source-engine",
        "repo_branch": "",
        "stable_commit": "ed8209c",
        "build_system": "waf",
        "patch_dir_name": "source-engine",
        "waf_game": "hl2",
        "estimated_time": 3,
        "estimated_space": 25,
    },
    {
        "name": "Half-Life 2: Episodic (Episodes 1 & 2)",
        "subfolder": "episodic",
        "repo_url": "https://github.com/nillerusr/source-engine",
        "repo_branch": "",
        "stable_commit": "ed8209c",
        "build_system": "waf",
        "patch_dir_name": "source-engine",
        "waf_game": "episodic",
        "estimated_time": 3,
        "estimated_space": 25,
    },
    {
        "name": "Half-Life: Source",
        "subfolder": "hl1",
        "repo_url": "https://github.com/nillerusr/source-engine",
        "repo_branch": "",
        "stable_commit": "ed8209c",
        "build_system": "waf",
        "patch_dir_name": "source-engine",
        "waf_game": "hl1",
        "estimated_time": 3,
        "estimated_space": 25,
    },
]

PORTAL_SOURCE_COMPONENTS = [
    {
        "name": "Portal",
        "subfolder": "portal",
        "repo_url": "https://github.com/nillerusr/source-engine",
        "repo_branch": "",
        "stable_commit": "ed8209c",
        "build_system": "waf",
        "patch_dir_name": "source-engine",
        "waf_game": "portal",
        "estimated_time": 3,
        "estimated_space": 25,
    },
]

SOURCE_LINK_FIXES = {
    "libvphysics.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libtogl.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libdatacache.dylib": [
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libvaudio_minimp3.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libmaterialsystem.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libvguimatsurface.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{thirdparty_prefix}/libfreetype.6.dylib", "@loader_path/libfreetype.6.dylib"),
        ("{thirdparty_prefix}/libfontconfig.1.dylib", "@loader_path/libfontconfig.1.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
    ],
    "libscenefilecache.dylib": [
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libsteam_api.dylib": [],
    "libServerBrowser.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{build_prefix}/stub_steam/libsteam_api.dylib", "@loader_path/libsteam_api.dylib"),
    ],
    "libinputsystem.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{build_prefix}/stub_steam/libsteam_api.dylib", "@loader_path/libsteam_api.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
    ],
    "libvideo_services.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libvgui2.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
    ],
    "libvtex_dll.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{thirdparty_prefix}/libjpeg.9.dylib", "@loader_path/libjpeg.9.dylib"),
        ("{thirdparty_prefix}/libpng16.16.dylib", "@loader_path/libpng16.16.dylib"),
        ("{thirdparty_prefix}/libz.1.dylib", "@loader_path/libz.1.3.1.dylib"),
    ],
    "libtier0.dylib": [],
    "libshaderapidx9.dylib": [
        ("{build_prefix}/togl/libtogl.dylib", "@loader_path/libtogl.dylib"),
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libGameUI.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{build_prefix}/stub_steam/libsteam_api.dylib", "@loader_path/libsteam_api.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
        ("{thirdparty_prefix}/libjpeg.9.dylib", "@loader_path/libjpeg.9.dylib"),
        ("{thirdparty_prefix}/libpng16.16.dylib", "@loader_path/libpng16.16.dylib"),
        ("{thirdparty_prefix}/libz.1.dylib", "@loader_path/libz.1.3.1.dylib"),
    ],
    "libstudiorender.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "liblauncher.dylib": [
        ("{build_prefix}/togl/libtogl.dylib", "@loader_path/libtogl.dylib"),
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{build_prefix}/stub_steam/libsteam_api.dylib", "@loader_path/libsteam_api.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
    ],
    "libfilesystem_stdio.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libstdshader_dx9.dylib": [
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libengine.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
        ("{build_prefix}/stub_steam/libsteam_api.dylib", "@loader_path/libsteam_api.dylib"),
        ("{thirdparty_prefix}/libSDL2-2.0.0.dylib", "@loader_path/libSDL2-2.0.0.dylib"),
        ("{thirdparty_prefix}/libjpeg.9.dylib", "@loader_path/libjpeg.9.dylib"),
        ("{thirdparty_prefix}/libz.1.dylib", "@loader_path/libz.1.3.1.dylib"),
        ("{thirdparty_prefix}/libcurl.4.dylib", "@loader_path/libcurl.4.dylib"),
    ],
    "libsoundemittersystem.dylib": [
        ("{build_prefix}/vstdlib/libvstdlib.dylib", "@loader_path/libvstdlib.dylib"),
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libpkgconf.7.dylib": [],
    "libpng16.16.dylib": [],
    "libfreetype.6.dylib": [
        ("{thirdparty_prefix}/libpng16.16.dylib", "@loader_path/libpng16.16.dylib"),
        ("{thirdparty_prefix}/libz.1.dylib", "@loader_path/libz.1.3.1.dylib"),
    ],
    "libz.1.3.1.dylib": [],
    "libjpeg.9.dylib": [],
    "libfontconfig.1.dylib": [
        ("{thirdparty_prefix}/libfreetype.6.dylib", "@loader_path/libfreetype.6.dylib"),
    ],
    "libcurl.4.dylib": [],
    "libedit.0.dylib": [],
    "libvstdlib.dylib": [
        ("{build_prefix}/tier0/libtier0.dylib", "@loader_path/libtier0.dylib"),
    ],
    "libopus.0.dylib": [],
}
